_prometheus_alumnos:
   resource: "@InformaticaPrometheusBundle/Controller/AlumnoController.php"
   type:     annotation
   
_prometheus_docentes:
    resource: "@InformaticaPrometheusBundle/Controller/DocenteController.php"
    type:     annotation
	
-prometheus_asignatura:
    resource: "@InformaticaPrometheusBundle/Controller/AsignaturaController.php"
    type:     annotation

