<?php

namespace Informatica\PrometheusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteRepository extends EntityRepository
{
}